### ISSUE TITLE
migration away from sqlite

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#32] opened 2022-03-25 14:13 UTC
newer versions of wikijs don't use sqlite.   We will need to sort that out.   It might be possible to migrate to a sql server and preload the wiki using sql?

**Comment by MarshallAsch** [comment] 2022-03-26 13:01
This is a duplicate of https://github.com/sci-oer/oo-resources/issues/7

**Closed as completed by MarshallAsch** 2022-03-26 13:01 UTC
Labels: duplicate
